"""
IES 生成器模块 (IES Generator)

负责单位校准、坐标系转换和 IES 文件格式化。
"""

from typing import List, Tuple, Dict
import numpy as np
import math


class CalibrationError(Exception):
    """校准错误"""
    pass


def calibrate_to_candela(brightness_data: np.ndarray,
                        total_lumens: float) -> np.ndarray:
    """
    将 Blender 渲染单位转换为坎德拉（cd）
    
    参数:
        brightness_data: NumPy 数组，形状为 (n_points, 3)，每行为 [theta, phi, brightness]
        total_lumens: 光源总流明值
    
    返回:
        校准后的数据，形状为 (n_points, 3)，每行为 [theta, phi, candela]
    
    校准原理：
        1. 计算所有采样点的亮度总和
        2. 计算校准因子：total_lumens / (brightness_sum * solid_angle_per_sample)
        3. 将每个亮度值乘以校准因子得到坎德拉值
    """
    if total_lumens <= 0:
        raise CalibrationError("总流明值必须大于 0")
    
    if len(brightness_data) == 0:
        raise CalibrationError("亮度数据不能为空")
    
    # 提取亮度值
    brightness_values = brightness_data[:, 2]
    
    # 计算亮度总和
    brightness_sum = np.sum(brightness_values)
    
    if brightness_sum <= 0:
        raise CalibrationError("亮度总和必须大于 0，请检查场景配置")
    
    # 计算校准因子
    # 简化版本：假设均匀分布
    # 实际应该考虑立体角权重
    calibration_factor = total_lumens / brightness_sum
    
    # 应用校准
    calibrated_data = brightness_data.copy()
    calibrated_data[:, 2] = brightness_values * calibration_factor
    
    return calibrated_data


def blender_to_ies_coordinates(blender_coords: Tuple[float, float, float]) -> Tuple[float, float, float]:
    """
    Blender Z-up 坐标系转 IES Y-up 坐标系
    
    参数:
        blender_coords: Blender 坐标 (x, y, z)
    
    返回:
        IES 坐标 (x, y, z)
    
    转换规则：
        Blender: X=右, Y=前, Z=上
        IES:     X=右, Y=上, Z=前
        
        IES_X = Blender_X
        IES_Y = Blender_Z
        IES_Z = Blender_Y
    """
    return (blender_coords[0], blender_coords[2], blender_coords[1])


def generate_ies_header(total_lumens: float,
                       num_vertical_angles: int,
                       num_horizontal_angles: int) -> str:
    """
    生成 IESNA LM-63-2002 文件头
    
    参数:
        total_lumens: 总流明值
        num_vertical_angles: 垂直角度数量
        num_horizontal_angles: 水平角度数量
    
    返回:
        IES 文件头字符串
    """
    header = f"""IESNA:LM-63-2002
[TEST] Kiro IES Generator
[MANUFAC] Kiro
[LUMCAT] Generated
[LUMINAIRE] Custom Fixture
[LAMPCAT] LED
[LAMP] LED
[MORE] Generated by Kiro IES Generator using Blender Cycles
[TILT] NONE
1 {total_lumens:.1f} 1.0 {num_vertical_angles} {num_horizontal_angles} 1 1 1.0 1.0 0.0
1.0 1.0 0.0
"""
    return header


def format_ies_data(calibrated_data: np.ndarray) -> str:
    """
    格式化 IES 数据部分
    
    参数:
        calibrated_data: 校准后的数据，形状为 (n_points, 3)，每行为 [theta, phi, candela]
    
    返回:
        格式化的 IES 数据字符串
    """
    # 提取唯一的角度值
    theta_values = np.unique(calibrated_data[:, 0])
    phi_values = np.unique(calibrated_data[:, 1])
    
    # 排序（升序）
    theta_values = np.sort(theta_values)
    phi_values = np.sort(phi_values)
    
    # 格式化角度列表
    data_str = ""
    
    # 垂直角度列表
    for theta in theta_values:
        data_str += f"{theta:.1f} "
    data_str += "\n"
    
    # 水平角度列表
    for phi in phi_values:
        data_str += f"{phi:.1f} "
    data_str += "\n"
    
    # 坎德拉值（按 C-Plane 格式组织）
    # 对于每个水平角度，输出所有垂直角度的坎德拉值
    for phi in phi_values:
        for theta in theta_values:
            # 查找对应的坎德拉值
            mask = (calibrated_data[:, 0] == theta) & (calibrated_data[:, 1] == phi)
            candela_values = calibrated_data[mask, 2]
            
            if len(candela_values) > 0:
                candela = candela_values[0]
            else:
                candela = 0.0
            
            data_str += f"{candela:.2f} "
        data_str += "\n"
    
    return data_str


def generate_ies_file(calibrated_data: np.ndarray,
                     total_lumens: float) -> str:
    """
    从校准数据生成完整的 IES 文件内容
    
    参数:
        calibrated_data: 校准后的数据，形状为 (n_points, 3)，每行为 [theta, phi, candela]
        total_lumens: 总流明值
    
    返回:
        完整的 IES 文件内容字符串
    """
    # 计算角度数量
    num_vertical_angles = len(np.unique(calibrated_data[:, 0]))
    num_horizontal_angles = len(np.unique(calibrated_data[:, 1]))
    
    # 生成文件头
    header = generate_ies_header(total_lumens, num_vertical_angles, num_horizontal_angles)
    
    # 格式化数据
    data = format_ies_data(calibrated_data)
    
    # 组合
    ies_content = header + data
    
    return ies_content


def validate_ies_compliance(ies_content: str) -> bool:
    """
    验证 IES 文件合规性
    
    参数:
        ies_content: IES 文件内容
    
    返回:
        True 如果符合 LM-63-2002 标准
    """
    # 基本验证
    if not ies_content.startswith("IESNA:LM-63"):
        return False
    
    # 检查必需的关键字
    required_keywords = ["[TEST]", "[MANUFAC]", "[LUMCAT]", "[TILT]"]
    for keyword in required_keywords:
        if keyword not in ies_content:
            return False
    
    return True
